/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.tfedorov.gradledependencies.softwarelibrary

import com.tfedorov.gradledependencies.booktransitive.Book


object SoftwareLibrary {

  def action(): String = " Software library has  " + Book.book
}
