/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.tfedorov.gradledependencies.softwarelibrary

import com.tfedorov.gradledependencies.booktransitive.Book


object SoftwareLibrary {

  def takeFromLibrary: String = " Take from the Software library - " + Book.book
}
