/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.tfedorov.gradledependencies.client

import com.tfedorov.gradledependencies.softwarelibrary.SoftwareLibrary
import com.tfedorov.gradledependencies.sciencelibrary.ScienceLibrary

object ClientApp extends App {

  println("Action 1: " + ScienceLibrary.action)
  println("Action 2: " + SoftwareLibrary.action)
}
