/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.tfedorov.gradledependencies.sciencelibrary

import com.tfedorov.gradledependencies.booktransitive.Book

object ScienceLibrary {

  def takeFromLibrary: String = " Take from the Science library - " + Book.book
}
