/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.tfedorov.gradledependencies.booktransitive

object Book {

  def book: String = " a book 'Machine Learning Yearning'. by Andrew Ng. (v1)"
}
