/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.tfedorov.gradledependencies.booktransitive

object Book {

  def book: String = " a book 'Programming in Scala Fifth Edition 5st edition.' by Martin Odersky (v2)"
}
