/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.tfedorov.gradledependencies.client

import com.tfedorov.gradledependencies.softwarelibrary.SoftwareLibrary
import com.tfedorov.gradledependencies.sciencelibrary.ScienceLibrary

object ClientApp extends App {

  println("Action 1: " + ScienceLibrary.takeFromLibrary)
  println("Action 2: " + SoftwareLibrary.takeFromLibrary)
}
