/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.tfedorov.elfunit
import com.tfedorov.gradledependencies.weapon.Weapon
object Elf {

  def action(): String = "Elf is using" +Weapon.using
}
